apiVersion: batch/v1
kind: CronJob
metadata:
  name: busybox-cronjob 
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
            command: ["/bin/sleep"]
            args: ["30"]
          restartPolicy: OnFailure
