apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvvol-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle 
  nfs:
    path: /opt/sfw
    server: k8scp   #<-- Edit to match cp node
    readOnly: false
