apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluserrolebindingreview
subjects:
- kind: User 
  name: securityaccount 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: sec-role 
  apiGroup: rbac.authorization.k8s.io
