apiVersion: v1
kind: PersistentVolume
metadata:
  name: reviewvol
spec:
  capacity:
    storage: 200M 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/nfs_vol
    server: k8scp
